### ISSUE TITLE
Can I use jquery template without html file and compile them by some tools like node js

### ISSUE THREAD

**Issue by jyjin** [BorisMoore/jquery-tmpl#184]

**Comment by BorisMoore** [comment]
No, jquery-tmpl only works with the HTML DOM - and also requires jQuery. So you can't use it on Node, unless you also use a Node.js HTML DOM implementation - and that scenario has not been tested. It is not designed for use on the server.

It sounds like it would be much better for you to use JsRender instead, which does not require a DOM, and is optimized also for use on Node.js.   See http://www.jsviews.com/#jsr-node-quickstart.
