### ISSUE TITLE
Nested tmpls

### ISSUE THREAD

**Issue by sebasladino** [BorisMoore/jquery-tmpl#188]
help, i need nested templates, example.

```javascript
<script type="text/x-jquery-tmpl" id="xxx">
    <div>
        FIRTS HTML TEMPLATE

        <script type="text/x-jquery-tmpl" id="xxx2">
                   OTHER HTML TEMPLATE
        </script>
    </div>
 </scrtip>
```

Thanks

**Comment by BorisMoore** [comment]
Sorry, jQuery templates is no longer maintained. You could take a look at https://github.com/BorisMoore/jquery-tmpl/blob/master/demos/samplesCore/composition.html, or better, switch to JsRender. See for example: 
- https://www.jsviews.com/#tagsyntax@composition
- https://www.jsviews.com/#samples/jsr/composition
- or this search result: https://www.jsviews.com/#search?s=composition

**Comment by sebasladino** [comment]
Thanks @BorisMoore for the answer, i see jsviews.

Thanks :+1:
