### ISSUE TITLE
$obj.tmpl().html() can not return whole html , i need a method to return this dom's whoe html ?

### ISSUE THREAD

**Issue by tomatojacky** [BorisMoore/jquery-tmpl#191]
```
<script id="companyTmpl" type="text/x-jquery-tmpl">
  country:${country}
  <div> sex:${sex}</div>
${age}
</script>

<script id="companyTmpl" type="text/x-jquery-tmpl">
  $(function() {
  var template="<div>${name}</div><div style="background:#ccc;">${infos}</div>";
    $.template("templateList", template);
    var data={
      name:"lucy"
    }
    data.infos=$("#companyTmpl").tmpl({country:"USA",sex:"girl",age:"18"}).html();
    $.tmpl('templateList',data).appendTo('#dataCompany');

  });
</script>
```

$obj.tmpl() , i need a method to return this dom's whole html ?
$obj.tmpl().html() can not return whole html

**Comment by BorisMoore** [comment]
jQuery templates (jquery-tmpl) are no longer supported or maintained. I strongly encourage you to switch to JsRender, which is more powerful, more performant, fully supported, and has simpler APIs.
http://www.jsviews.com/#jsr-quickstart

**Comment by tomatojacky** [comment]
@BorisMoore  ok,thanks,i will try

**Comment by tomatojacky** [comment]
@BorisMoore  $("#companyTmpl").tmpl({country:"USA",sex:"girl",age:"18"}).wrapAll('div').parent().html(); can get all html ,i'll read the jsviews todady ,thank you
